### ISSUE TITLE
Cannot delete user after enabling

### ISSUE THREAD

**Issue by Trumeet** [ReFlar/polls#56]
### Instructions (MUST READ FIRST)

Before we can address your issues and concerns with the behavior of our work, we require every bit of detail from you to the fullest extent of this form. If this form is not properly filled out to it's entirity, we, ReFlar, reserve the right to close your issue due to lack of information thereof as well as not following instructions.

* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Please Mentally Go Over the Following Items Before Filling Out this Form:

* Can you reproduce this problem in debug mode?
~~I'm lazy and I'd like to skip this :sleeping: ~~
* Are you running the latest version of this extension?
Yes, I've installed it today.
* Is your Flarum up-to-date?
Beta 8.

### Description

[Description of the bug or feature]
After enabling, I cannot delete a specificated user. After disabling this plugin I cannot delete as well. Maybe I think it modified the database?

### Steps to Reproduce

1. [First Step]
Open a user's page.
2. [Second Step]
Delete it.
3. [and so on...]
Web page shows that there is an error (Server returns 500)

**Expected Behavior:** [What you expected to happen]
It is deleted correctly without any errors.

**Actual Behavior:** [What actually happened (screenshots are welcomed!)]
See information below.

### Flarum/Server/Client Information
I'm using https://github.com/mondediefr/docker-flarum .

## Technical Details

- Version of Flarum (x.y.z): `v0.1.0-beta.8.1`
- Version of extension (x.y.z): `1.3.2`
- [OPTIONAL] Website URL where the bug is visible (https://example.com): productforum.yuuta.moe (Chinese)
- The webserver you are running (Apache, Nginx, etc): Nginx
- PHP version (x.y.z): `PHP7.2`
- Hosted environment (Shared, VPS, etc): GCE (Docker)
- Hosting provider (https://some-amazing-provider.com): Is it necessary? The domain is registered in Namecheap.

## Flarum Info

```
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.13
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, json, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, mysqlnd, Phar, pdo_mysql, Zend OPcache
+-----------------------------------+------------------+--------+
| Flarum Extensions                 |                  |        |
+-----------------------------------+------------------+--------+
| ID                                | Version          | Commit |
+-----------------------------------+------------------+--------+
| flarum-approval                   | v0.1.0-beta.8    |        |
| flarum-bbcode                     | v0.1.0-beta.8    |        |
| flarum-emoji                      | v0.1.0-beta.8    |        |
| flarum-lang-english               | v0.1.0-beta.8    |        |
| flarum-flags                      | v0.1.0-beta.8.1  |        |
| flarum-likes                      | v0.1.0-beta.8.1  |        |
| flarum-lock                       | v0.1.0-beta.8    |        |
| flarum-mentions                   | v0.1.0-beta.8.1  |        |
| flarum-statistics                 | v0.1.0-beta.8    |        |
| flarum-sticky                     | v0.1.0-beta.8    |        |
| flarum-subscriptions              | v0.1.0-beta.8    |        |
| flarum-suspend                    | v0.1.0-beta.8    |        |
| flarum-tags                       | v0.1.0-beta.8.2  |        |
| csineneo-lang-simplified-chinese  | v0.1.0-beta.8.20 |        |
| csineneo-lang-traditional-chinese | v0.1.0-beta.8.19 |        |
| flagrow-analytics                 | 0.7.0            |        |
| wiwatsrt-best-answer              | v0.2.0           |        |
| fof-links                         | 0.1.1            |        |
| flagrow-upload                    | 0.7.1            |        |
| flarum-markdown                   | v0.1.0-beta.8    |        |
| reflar-gamification               | 3.1.1            |        |
| fof-spamblock                     | 0.2.1            |        |
| reflar-reactions                  | 1.0.0-beta.5.1   |        |
| fof-user-bio                      | 0.1.1            |        |
| reflar-nightmode                  | 0.2.0            |        |
| flagrow-terms                     | 0.3.1            |        |
| flagrow-bazaar                    | 0.3.9            |        |
| flagrow-sitemap                   | 0.2.0            |        |
+-----------------------------------+------------------+--------+
Base URL: https://productforum.yuuta.moe
Installation path: /flarum/app
Debug mode: off
```

## Log Files

```
[2019-01-18 05:10:40] production.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`flarum`.`flarum_poll_votes`, CONSTRAINT `poll_votes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `flarum_users` (`id`)) in /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /flarum/app/vendor/illuminate/database/Connection.php(483): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /flarum/app/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete from `fl...', Array)
#3 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('delete from `fl...', Array, Object(Closure))
#4 /flarum/app/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('delete from `fl...', Array, Object(Closure))
#5 /flarum/app/vendor/illuminate/database/Connection.php(435): Illuminate\Database\Connection->affectingStatement('delete from `fl...', Array)
#6 /flarum/app/vendor/illuminate/database/Query/Builder.php(2252): Illuminate\Database\Connection->delete('delete from `fl...', Array)
#7 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(842): Illuminate\Database\Query\Builder->delete()
#8 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(814): Illuminate\Database\Eloquent\Builder->delete()
#9 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(785): Illuminate\Database\Eloquent\Model->performDeleteOnModel()
#10 /flarum/app/vendor/flarum/core/src/User/Command/DeleteUserHandler.php(57): Illuminate\Database\Eloquent\Model->delete()
#11 /flarum/app/vendor/illuminate/bus/Dispatcher.php(90): Flarum\User\Command\DeleteUserHandler->handle(Object(Flarum\User\Command\DeleteUser))
#12 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\User\Command\DeleteUser))
#13 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\User\Command\DeleteUser))
#14 /flarum/app/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /flarum/app/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\User\Command\DeleteUser))
#16 /flarum/app/vendor/flarum/core/src/Api/Controller/DeleteUserController.php(39): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\User\Command\DeleteUser))
#17 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractDeleteController.php(26): Flarum\Api\Controller\DeleteUserController->delete(Object(Zend\Diactoros\ServerRequest))
#18 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Api\Controller\AbstractDeleteController->handle(Object(Zend\Diactoros\ServerRequest))
#19 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#20 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#21 /flarum/app/vendor/flagrow/terms/src/Middlewares/RegisterMiddleware.php(59): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#22 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flagrow\Terms\Middlewares\RegisterMiddleware->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#23 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#24 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#25 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#26 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#27 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#28 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#29 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#30 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#31 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#32 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#33 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#34 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#35 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#36 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#37 /flarum/app/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#38 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#39 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#40 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#41 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#42 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#43 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#44 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#45 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#46 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#47 /flarum/app/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#48 /flarum/app/public/index.php(22): Flarum\Http\Server->listen()
#49 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`flarum`.`flarum_poll_votes`, CONSTRAINT `poll_votes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `flarum_users` (`id`)) in /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
Stack trace:
#0 /flarum/app/vendor/illuminate/database/Connection.php(483): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /flarum/app/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete from `fl...', Array)
#2 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('delete from `fl...', Array, Object(Closure))
#3 /flarum/app/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('delete from `fl...', Array, Object(Closure))
#4 /flarum/app/vendor/illuminate/database/Connection.php(435): Illuminate\Database\Connection->affectingStatement('delete from `fl...', Array)
#5 /flarum/app/vendor/illuminate/database/Query/Builder.php(2252): Illuminate\Database\Connection->delete('delete from `fl...', Array)
#6 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(842): Illuminate\Database\Query\Builder->delete()
#7 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(814): Illuminate\Database\Eloquent\Builder->delete()
#8 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(785): Illuminate\Database\Eloquent\Model->performDeleteOnModel()
#9 /flarum/app/vendor/flarum/core/src/User/Command/DeleteUserHandler.php(57): Illuminate\Database\Eloquent\Model->delete()
#10 /flarum/app/vendor/illuminate/bus/Dispatcher.php(90): Flarum\User\Command\DeleteUserHandler->handle(Object(Flarum\User\Command\DeleteUser))
#11 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\User\Command\DeleteUser))
#12 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\User\Command\DeleteUser))
#13 /flarum/app/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /flarum/app/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\User\Command\DeleteUser))
#15 /flarum/app/vendor/flarum/core/src/Api/Controller/DeleteUserController.php(39): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\User\Command\DeleteUser))
#16 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractDeleteController.php(26): Flarum\Api\Controller\DeleteUserController->delete(Object(Zend\Diactoros\ServerRequest))
#17 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Api\Controller\AbstractDeleteController->handle(Object(Zend\Diactoros\ServerRequest))
#18 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#19 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#20 /flarum/app/vendor/flagrow/terms/src/Middlewares/RegisterMiddleware.php(59): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#21 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flagrow\Terms\Middlewares\RegisterMiddleware->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#23 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#25 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#26 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#27 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#28 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#29 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#30 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#31 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#32 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#33 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#34 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#35 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#36 /flarum/app/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#37 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#38 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#39 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#40 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#41 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#42 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#43 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#44 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#45 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#46 /flarum/app/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#47 /flarum/app/public/index.php(22): Flarum\Http\Server->listen()
#48 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`flarum`.`flarum_poll_votes`, CONSTRAINT `poll_votes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `flarum_users` (`id`)) (SQL: delete from `flarum_users` where `id` = 29) in /flarum/app/vendor/illuminate/database/Connection.php:664
Stack trace:
#0 /flarum/app/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('delete from `fl...', Array, Object(Closure))
#1 /flarum/app/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('delete from `fl...', Array, Object(Closure))
#2 /flarum/app/vendor/illuminate/database/Connection.php(435): Illuminate\Database\Connection->affectingStatement('delete from `fl...', Array)
#3 /flarum/app/vendor/illuminate/database/Query/Builder.php(2252): Illuminate\Database\Connection->delete('delete from `fl...', Array)
#4 /flarum/app/vendor/illuminate/database/Eloquent/Builder.php(842): Illuminate\Database\Query\Builder->delete()
#5 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(814): Illuminate\Database\Eloquent\Builder->delete()
#6 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(785): Illuminate\Database\Eloquent\Model->performDeleteOnModel()
#7 /flarum/app/vendor/flarum/core/src/User/Command/DeleteUserHandler.php(57): Illuminate\Database\Eloquent\Model->delete()
#8 /flarum/app/vendor/illuminate/bus/Dispatcher.php(90): Flarum\User\Command\DeleteUserHandler->handle(Object(Flarum\User\Command\DeleteUser))
#9 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\User\Command\DeleteUser))
#10 /flarum/app/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\User\Command\DeleteUser))
#11 /flarum/app/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /flarum/app/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\User\Command\DeleteUser))
#13 /flarum/app/vendor/flarum/core/src/Api/Controller/DeleteUserController.php(39): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\User\Command\DeleteUser))
#14 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractDeleteController.php(26): Flarum\Api\Controller\DeleteUserController->delete(Object(Zend\Diactoros\ServerRequest))
#15 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Api\Controller\AbstractDeleteController->handle(Object(Zend\Diactoros\ServerRequest))
#16 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#17 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#18 /flarum/app/vendor/flagrow/terms/src/Middlewares/RegisterMiddleware.php(59): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#19 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flagrow\Terms\Middlewares\RegisterMiddleware->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#20 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#21 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#23 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#25 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#26 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#27 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#28 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#29 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#30 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#31 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#32 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#33 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#34 /flarum/app/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#35 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#36 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#37 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#38 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#39 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#40 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#41 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#42 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#43 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#44 /flarum/app/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#45 /flarum/app/public/index.php(22): Flarum\Http\Server->listen()
#46 {main}  
```

**Comment by Ralkage** [comment]
@Trumeet still an issue?

**Comment by Trumeet** [comment]
> @Trumeet still an issue?

@Ralkage Sorry, I've already uninstalled Flarum 😢 

Finger crossed, I wish I will re-use it on one day.

**Comment by Ralkage** [comment]
@Trumeet what was your reason(s) for uninstalling Flarum? Did you pick another forum software? Feedback would be awesome so I could relay this to the ReFlar team as well as the staff over at Flarum Discuss :)

I'll be closing this issue, but feel free to still respond after it's closed!

**Comment by Trumeet** [comment]
@Ralkage It's just becaust my forum was not used a lot :D
